"""Add security question fields to User

Revision ID: dde5a132edb9
Revises: dccbfb781553
Create Date: 2026-09-13 06:02:24.204100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde5a132edb9'
down_revision = 'dccbfb781553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('security_answer_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security_answer_hash')
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###
